presubmits:
  - name: presubmit-kbp-test
    decorate: true
    always_run: true
    spec:
      containers:
      - image: node:16-alpine3.16
        command:
        - "/bin/sh"
        - "-c"
        - |
          yarn install
          yarn test:all
          
  - name: presubmit-kbp-lint
    decorate: true
    always_run: true
    spec:
      containers:
      - image: node:16-alpine3.16
        command:
        - "/bin/sh"
        - "-c"
        - |
          yarn install
          yarn lint:all
